//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsInParkingLotPath_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsInParkingLotPath_Header()
        {
            this.CarsInParkingLotPath_Body = new HashSet<CarsInParkingLotPath_Body>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> GridId { get; set; }
        public int Direction { get; set; }
        public System.DateTime CreateUTCTime { get; set; }
    
        public virtual Cars Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsInParkingLotPath_Body> CarsInParkingLotPath_Body { get; set; }
        public virtual ParkingGrid ParkingGrid { get; set; }
    }
}
