//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.ETAs = new HashSet<ETAs>();
            this.PushPhoneDetail = new HashSet<PushPhoneDetail>();
        }
    
        public int Id { get; set; }
        public string CarNumber { get; set; }
        public string CarType { get; set; }
        public Nullable<int> CarPurposeTypeID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public bool Void { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateUTCTime { get; set; }
        public int LastUpdateUserId { get; set; }
        public System.DateTime LastUpdateUTCTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETAs> ETAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PushPhoneDetail> PushPhoneDetail { get; set; }
        public virtual CarPurposeTypes CarPurposeTypes { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
