//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingLotModelEntities : DbContext
    {
        public ParkingLotModelEntities()
            : base("name=ParkingLotModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ETAs> ETAs { get; set; }
        public virtual DbSet<ParkingGrid> ParkingGrid { get; set; }
        public virtual DbSet<ParkingLotAreas> ParkingLotAreas { get; set; }
        public virtual DbSet<ParkingLotFloors> ParkingLotFloors { get; set; }
        public virtual DbSet<CarsInParkingLotPath_Body> CarsInParkingLotPath_Body { get; set; }
        public virtual DbSet<CarsInParkingLotPath_Header> CarsInParkingLotPath_Header { get; set; }
        public virtual DbSet<vw_ParkingLotGridRemain> vw_ParkingLotGridRemain { get; set; }
        public virtual DbSet<News_Header> News_Header { get; set; }
        public virtual DbSet<Sensors> Sensors { get; set; }
        public virtual DbSet<News_Body> News_Body { get; set; }
    }
}
