//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingLotsDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Period { get; set; }
        public string Charge { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int CarGrid { get; set; }
        public int MotoGrid { get; set; }
        public bool Void { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
