//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushPhoneDetail
    {
        public byte PhoneTypeID { get; set; }
        public string DeviceID { get; set; }
        public string Token { get; set; }
        public string PhoneNumber { get; set; }
        public bool Void { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual PushPhoneType PushPhoneType { get; set; }
    }
}
