//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ParkingLotGridRemain
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Void { get; set; }
        public string 樓層名稱 { get; set; }
        public int 停車格數 { get; set; }
        public int 剩餘停車格數 { get; set; }
        public System.DateTime 最後更新時間 { get; set; }
        public Nullable<bool> NoneFloor { get; set; }
    }
}
