//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WbParkSystemEntities : DbContext
    {
        public WbParkSystemEntities()
            : base("name=WbParkSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnouncementDetail> AnnouncementDetail { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<PushPhoneType> PushPhoneType { get; set; }
        public virtual DbSet<CarPurposeTypes> CarPurposeTypes { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<ETAs> ETAs { get; set; }
        public virtual DbSet<ParkingArea> ParkingArea { get; set; }
        public virtual DbSet<ParkingLotsDetail> ParkingLotsDetail { get; set; }
        public virtual DbSet<ParkingLotsFloor> ParkingLotsFloor { get; set; }
        public virtual DbSet<PushPhoneDetail> PushPhoneDetail { get; set; }
        public virtual DbSet<ParkingLotsRecord> ParkingLotsRecord { get; set; }
        public virtual DbSet<ParkingLotsRecord_HT> ParkingLotsRecord_HT { get; set; }
    }
}
