//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReslangMUI {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MUI() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.Core.Infrastructures.Implementations.MUI", typeof(MUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失敗次數 的當地語系化字串。
        /// </summary>
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住址 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內文 的當地語系化字串。
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子群組 的當地語系化字串。
        /// </summary>
        public static string ChildId {
            get {
                return ResourceManager.GetString("ChildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 宣告類型 的當地語系化字串。
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 宣告值 的當地語系化字串。
        /// </summary>
        public static string ClaimValue {
            get {
                return ResourceManager.GetString("ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立者 的當地語系化字串。
        /// </summary>
        public static string CreateUserId {
            get {
                return ResourceManager.GetString("CreateUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說明描述 的當地語系化字串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示名稱 的當地語系化字串。
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件地址 的當地語系化字串。
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件驗證狀態 的當地語系化字串。
        /// </summary>
        public static string EMailConfirmed {
            get {
                return ResourceManager.GetString("EMailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組識別碼 的當地語系化字串。
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組名稱 的當地語系化字串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 識別碼 的當地語系化字串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後活動時間 的當地語系化字串。
        /// </summary>
        public static string LastActivityTime {
            get {
                return ResourceManager.GetString("LastActivityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後一次登入失敗時間 的當地語系化字串。
        /// </summary>
        public static string LastLoginFailTime {
            get {
                return ResourceManager.GetString("LastLoginFailTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後解除鎖定時間 的當地語系化字串。
        /// </summary>
        public static string LastUnlockedTime {
            get {
                return ResourceManager.GetString("LastUnlockedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後更新時間 的當地語系化字串。
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後更新者 的當地語系化字串。
        /// </summary>
        public static string LastUpdateUserId {
            get {
                return ResourceManager.GetString("LastUpdateUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 存取層級 的當地語系化字串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 鎖定狀態 的當地語系化字串。
        /// </summary>
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 鎖定結束日期 的當地語系化字串。
        /// </summary>
        public static string LockoutEndDate {
            get {
                return ResourceManager.GetString("LockoutEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入提供者名稱 的當地語系化字串。
        /// </summary>
        public static string LoginProvider {
            get {
                return ResourceManager.GetString("LoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄時間 的當地語系化字串。
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作者 的當地語系化字串。
        /// </summary>
        public static string LogUserName {
            get {
                return ResourceManager.GetString("LogUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本地化訊息識別碼 的當地語系化字串。
        /// </summary>
        public static string MessageResourceKey {
            get {
                return ResourceManager.GetString("MessageResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作紀錄代碼 的當地語系化字串。
        /// </summary>
        public static string OpreationCode {
            get {
                return ResourceManager.GetString("OpreationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父群組 的當地語系化字串。
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加密後密碼 的當地語系化字串。
        /// </summary>
        public static string PasswordHash {
            get {
                return ResourceManager.GetString("PasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼驗證狀態 的當地語系化字串。
        /// </summary>
        public static string PhoneConfirmed {
            get {
                return ResourceManager.GetString("PhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼 的當地語系化字串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本資料識別碼 的當地語系化字串。
        /// </summary>
        public static string ProfileId {
            get {
                return ResourceManager.GetString("ProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提供者鍵值 的當地語系化字串。
        /// </summary>
        public static string ProviderKey {
            get {
                return ResourceManager.GetString("ProviderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼重設權杖 的當地語系化字串。
        /// </summary>
        public static string ResetPasswordToken {
            get {
                return ResourceManager.GetString("ResetPasswordToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱 的當地語系化字串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 安全戳記 的當地語系化字串。
        /// </summary>
        public static string SecurityStamp {
            get {
                return ResourceManager.GetString("SecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 兩步驟驗證 的當地語系化字串。
        /// </summary>
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網路位址 的當地語系化字串。
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者識別碼 的當地語系化字串。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
    }
}
