//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLotWebApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebPages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPages() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkingLotWebApp.App_GlobalResources.WebPages", typeof(WebPages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛資訊 的當地語系化字串。
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增車輛 的當地語系化字串。
        /// </summary>
        public static string Cars_Create_New {
            get {
                return ResourceManager.GetString("Cars_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除車輛 的當地語系化字串。
        /// </summary>
        public static string Cars_Delete {
            get {
                return ResourceManager.GetString("Cars_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛詳細資訊 的當地語系化字串。
        /// </summary>
        public static string Cars_Details {
            get {
                return ResourceManager.GetString("Cars_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 車輛清單 的當地語系化字串。
        /// </summary>
        public static string Cars_Lists {
            get {
                return ResourceManager.GetString("Cars_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這台車 的當地語系化字串。
        /// </summary>
        public static string Cars_This {
            get {
                return ResourceManager.GetString("Cars_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統公告 的當地語系化字串。
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增公告 的當地語系化字串。
        /// </summary>
        public static string News_Create_New {
            get {
                return ResourceManager.GetString("News_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除公告 的當地語系化字串。
        /// </summary>
        public static string News_Delete {
            get {
                return ResourceManager.GetString("News_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告標題 的當地語系化字串。
        /// </summary>
        public static string News_Header {
            get {
                return ResourceManager.GetString("News_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這則公告 的當地語系化字串。
        /// </summary>
        public static string News_This {
            get {
                return ResourceManager.GetString("News_This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公告期間 的當地語系化字串。
        /// </summary>
        public static string NewsDurtion {
            get {
                return ResourceManager.GetString("NewsDurtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈者 的當地語系化字串。
        /// </summary>
        public static string NewsPoster {
            get {
                return ResourceManager.GetString("NewsPoster", resourceCulture);
            }
        }
    }
}
